### PR TITLE
Add forced-perspective chaos effect

### PR DESCRIPTION
**Pull request by The0x539**

### CODE REVIEW

**Comment by zelzmiy** [comment]
Looks good, however add a check to update so that the effect can be disabled mid-game, otherwise it requires a restart to disable

**Comment by wafflethings** [comment]
Lgtm

**Comment by Hydraxous** [comment]
epic

**Comment by The0x539** [comment]
> otherwise it requires a restart to disable

i intended for this to persist for already-spawned enemies but on closer inspection I misread the drone mitosis code


> Looks good, however add a check to update so that the effect can be disabled mid-game, otherwise it requires a restart to disable

**Comment by zelzmiy** [comment]
LGTM

**Pull request merged**
